title: Deepali L. Kundnani # your name (or website title) here
logo: "/images/Exec pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bioinformatics Ph.D. Student 
  <br>
  Georgia Institute of Technology
  <br><br>
  <img src="/logos/gs.jpg" width="20" height="16" alt="https://scholar.google.com/citations?user=RdAQkxwAAAAJ&hl=en&oi=ao">
  <a href="https://scholar.google.com/citations?user=RdAQkxwAAAAJ&hl=en&oi=ao">  Google Scholar </a> 
  <br>
  <img src="/logos/ln.png" width="20" height="20" alt="https://www.linkedin.com/in/deepalik/"> 
  <a href="https://www.linkedin.com/in/deepalik/"> LinkedIn  </a> 
  <br>
  <img src="/logos/pdf.jpg" width="20" height="20" alt="/pdf/DK_CV_2021[08].pdf"> 
  <a href="pdf/DLK_CV_2022[10].pdf">Curriculum Vitae</a> 
  <br>
  <img src="/logos/css.jpg" width="20" height="20" alt="https://atlanta.ashanet.org/blog/donation_profiles/deepali-l-kundnani-2/"> 
  <a href="https://atlanta.ashanet.org/blog/donation_profiles/deepali-l-kundnani-2/">Community Service Profile</a> 
  <br>
  <img src="/logos/O.png" width="20" height="20" alt="mailto:deepali.kundnani@gatech.edu"> 
  <a href="mailto:deepali.kundnani@gatech.edu">Email</a> 
  <br>




theme: jekyll-theme-minimal
google_analytics: G-ZKYQ2F24J1 # your Google Analytics tracking ID here


